/**
 * Base de Dados Estruturada de Plantas Medicinais do Cerrado e Biomas Brasileiros
 * Acervo e Herbário Digital — Raízes do Cerrado
 */

export const plantsData = [
  {
    id: "arnica-do-campo",
    code: "ESP-001",
    namePopular: "Arnica-do-campo",
    nameScientific: "Lychnophora pinaster",
    family: "Asteraceae",
    region: "Cerrado",
    macroRegions: ["Centro-Oeste", "Sudeste", "Nordeste"],
    regionsSecondary: ["Mata Atlântica (Campos Rupestres)"],
    shortDesc: "Arbusto típico dos campos rupestres do Cerrado, célebre por suas propriedades anti-inflamatórias e cicatrizantes nas comunidades tradicionais.",
    characteristics: "Arbusto ereto de 1 a 3 metros de altura, com folhas estreitas e rígidas semelhantes a agulhas de pinheiro, cobertas por uma fina pelugem esbranquiçada. Suas flores são pequenos capítulos alaranjados a amarelados no topo dos ramos.",
    occurrence: "Endêmica do Brasil, com ocorrência marcante nas serras dos estados de Minas Gerais, Goiás, Bahia e no Distrito Federal em altitudes acima de 900 metros.",
    traditionalUse: "Extratos alcoólicos (garrafadas ou macerados) e tinturas das folhas e ramos aplicados via tópica para contusões, dores musculares, traumatismos, hematomas e reumatismo.",
    curiosities: "É conhecida como a 'verdadeira arnica brasileira' para diferenciá-la da Arnica montana europeia. Por crescer em solos rochosos e pobres, possui óleo essencial altamente concentrado em sesquiterpenos com forte ação analgésica.",
    precautions: "Uso estritamente externo. Não deve ser ingerida ou aplicada sobre feridas abertas e sangramentos devido à potencial toxicidade hepática por alcaloides pirrolizidínicos.",
    sources: "EMBRAPA Cerrados; Farmacopeia Popular do Brasil; FIOCRUZ - Plantas Medicinais do Cerrado.",
    image: "assets/arnica_do_campo.png",
    conservationStatus: "Vulnerável (extrativismo predatório)",
    partUsed: "Folhas, ramos jovens e inflorescências"
  },
  {
    id: "barbatimao",
    code: "ESP-002",
    namePopular: "Barbatimão",
    nameScientific: "Stryphnodendron adstringens",
    family: "Fabaceae",
    region: "Cerrado",
    macroRegions: ["Centro-Oeste", "Sudeste", "Norte", "Nordeste"],
    regionsSecondary: ["Caatinga", "Pantanal"],
    shortDesc: "Árvore sagrada para a medicina popular do Cerrado, consagrada como uma das maiores fontes naturais de taninos cicatrizantes.",
    characteristics: "Árvore de porte médio (4 a 8 metros), tronco tortuoso com casca espessa e fendida. Suas folhas são compostas bipinadas e os frutos são vagens achatadas de cor marrom-escura.",
    occurrence: "Amplamente distribuída no bioma Cerrado, especialmente nas savanas arbóreas dos estados de São Paulo, Minas Gerais, Mato Grosso, Mato Grosso do Sul, Goiás, Tocantins e Bahia.",
    traditionalUse: "Decocção ou chá da casca para lavagem de feridas, queimaduras, inflamações de garganta, úlceras gástricas e higiene íntima pós-parto, dada sua poderosa ação adstringente e antimicrobiana.",
    curiosities: "Pesquisas científicas brasileiras comprovaram que a pomada de extrato de Barbatimão acelera a reepitelização da pele em tempo recorde, sendo aprovada na Farmacopeia Brasileira como fitoterápico oficial.",
    precautions: "Em doses elevadas por via oral pode causar irritação gástrica e constipação grave devido à alta concentração de taninos. Contraindicado na gravidez.",
    sources: "FIOCRUZ (Plantas Medicinais no SUS); Universidade Federal de Goiás (UFG); Farmacopeia Brasileira.",
    image: "assets/barbatimao.png",
    conservationStatus: "Pouco Preocupante (exige manejo sustentável)",
    partUsed: "Casca do tronco e entrecasca"
  },
  {
    id: "cagaita",
    code: "ESP-003",
    namePopular: "Cagaita",
    nameScientific: "Eugenia dysenterica",
    family: "Myrtaceae",
    region: "Cerrado",
    macroRegions: ["Centro-Oeste", "Sudeste", "Nordeste"],
    regionsSecondary: ["Caatinga"],
    shortDesc: "Fruteira nativa do Cerrado com propriedades duplas singulares: os frutos e as folhas atuam de formas opostas no sistema digestivo.",
    characteristics: "Árvore de 4 a 10 metros, com copa arredondada, casca suberosa (parecida com cortiça) e folhas glabras verde-brilhantes. Produz pequenas flores brancas perfumadas e frutos amarelos esféricos e suculentos.",
    occurrence: "Nativa do Cerrado central brasileiro, ocorrendo em solos arenosos e bem drenados do Planalto Central, Minas Gerais, Goiás e Bahia.",
    traditionalUse: "O chá das folhas jovens é tradicionalmente empregado para combater diarreias e desinterias. Já os frutos consumidos in natura quentes do sol ou em excesso possuem efeito laxativo acentuado.",
    curiosities: "Diz o ditado popular do Cerrado: 'Quem come cagaita no sol cagando fica'. O nome científico 'dysenterica' refere-se justamente a este efeito intestinal imediato do fruto aquecido.",
    precautions: "Evitar o consumo dos frutos expostos ao calor prolongado. O chá das folhas não deve ser usado por quem sofre de constipação crônica.",
    sources: "EMBRAPA Recursos Genéticos e Biotecnologia; Rede Cerrado; Livro 'Frutos e Plantas do Cerrado'.",
    image: "assets/cagaita.png",
    conservationStatus: "Pouco Preocupante",
    partUsed: "Folhas (chá) e Frutos (uso alimentar/medicinal)"
  },
  {
    id: "carqueja",
    code: "ESP-004",
    namePopular: "Carqueja",
    nameScientific: "Baccharis trimera",
    family: "Asteraceae",
    region: "Caatinga",
    macroRegions: ["Norte", "Nordeste", "Centro-Oeste", "Sudeste", "Sul"],
    regionsSecondary: ["Cerrado", "Mata Atlântica", "Pampa"],
    shortDesc: "Planta medicinal de hastes aladas sem folhas verdadeiras, indispensável na sabedoria popular brasileira para cuidados digestivos e hepáticos.",
    characteristics: "Subarbusto ereto de 0,5 a 1,2 metro, caracterizado por caules verdes achatados com três alas membranáceas (por isso 'trimera') que realizam a fotossíntese no lugar das folhas.",
    occurrence: "Ocorre espontaneamente em terrenos abertos, pastagens e campos de altitude da Caatinga, Cerrado, Mata Atlântica e Pampa de norte a sul do Brasil.",
    traditionalUse: "Infusão das hastes verdes para problemas de fígado, má digestão, azia, controle auxiliar da glicemia e como tônico amargo depurativo do sangue.",
    curiosities: "Seu sabor intensamente amargo é atribuído às lactonas sesquiterpênicas e aos flavonoides como a hispidulina, responsáveis pelo estímulo à secreção biliar.",
    precautions: "Contraindicada durante a gravidez (pode estimular contrações uterinas) e amamentação, assim como para hipotensos e diabéticos em uso de medicação sem supervisão.",
    sources: "ANVISA - Formulário de Fitoterápicos da Farmacopeia Brasileira; UFRGS - Plantas Medicinais do Sul.",
    image: "assets/carqueja.png",
    conservationStatus: "Pouco Preocupante",
    partUsed: "Hastes verdes aladas"
  },
  {
    id: "jatoba",
    code: "ESP-005",
    namePopular: "Jatobá-do-Cerrado",
    nameScientific: "Hymenaea courbaril",
    family: "Fabaceae",
    region: "Cerrado",
    macroRegions: ["Norte", "Nordeste", "Centro-Oeste", "Sudeste"],
    regionsSecondary: ["Amazônia", "Mata Atlântica"],
    shortDesc: "Árvore majestosa do bioma, cujos frutos e resinas são tesouros de energia, fortificantes respiratórios e sustentabilidade.",
    characteristics: "Árvore frondosa que pode atingir de 15 a 30 metros. Possui casca lisa avermelhada e frutos em forma de vagem lenhosa dura contendo uma farinha amarelada nutritiva e adocicada ao redor das sementes.",
    occurrence: "Presente em áreas de Cerradão, matas de galeria da Amazônia e florestas tropicais da Mata Atlântica.",
    traditionalUse: "O chá ou xarope da casca e da resina (jutaicica) é usado para tosses, bronquites, asma e como tônico energizante. A farinha do fruto é rica em ferro e cálcio.",
    curiosities: "Sua resina fóssil ou recente que escorre do tronco é conhecida como copal do Jatobá e era utilizada por povos indígenas para selar canoas e produzir vernizes naturais.",
    precautions: "O consumo da casca em excesso pode irritar a mucosa gástrica em pessoas sensíveis. A farinha deve ser conservada seca para evitar fungos.",
    sources: "Instituto Pesquisas Ecológicas (IPÊ); EMBRAPA Amazônia Oriental; Saberes dos Povos da Floresta.",
    image: "assets/jatoba.png",
    conservationStatus: "Pouco Preocupante",
    partUsed: "Casca, entrecasca, farinha do fruto e resina"
  },
  {
    id: "mangaba",
    code: "ESP-006",
    namePopular: "Mangaba",
    nameScientific: "Hancornia speciosa",
    family: "Apocynaceae",
    region: "Cerrado",
    macroRegions: ["Nordeste", "Centro-Oeste", "Sudeste"],
    regionsSecondary: ["Caatinga", "Mata Atlântica (Restingas)"],
    shortDesc: "Fruta símbolo de Sergipe e do Cerrado, cujo látex e casca possuem alto valor terapêutico na medicina tradicional sertaneja.",
    characteristics: "Árvore de pequeno a médio porte (3 a 7 metros), de tronco tortuoso e ramos pendentes. Ao ser ferida, exuda abundante látex branco espesso.",
    occurrence: "Nativa de áreas abertas de Cerrado, tabuleiros costeiros e restingas da Caatinga e Mata Atlântica do Nordeste e Centro-Oeste.",
    traditionalUse: "O látex diluído em água é usado popularmente para tratar luxações, fraturas, pancadas e úlceras. O chá da casca é indicado para hipertensão e diabetes.",
    curiosities: "O nome 'Mangaba' vem do Tupi-Guarani e significa 'coisa boa de comer'. O látex de Mangaba foi explorado historicamente durante a Segunda Guerra Mundial para produção de borracha nativa.",
    precautions: "O látex puro não deve ser ingerido sem a devida diluição e orientação, pois pode causar diarreias e reações alérgicas severas em pessoas sensíveis ao látex.",
    sources: "EMBRAPA Tabuleiros Costeiros; Coleção Plantas da Biodiversidade Brasileira (MMA).",
    image: "assets/mangaba_svg",
    conservationStatus: "Vulnerável por fragmentação de habitat",
    partUsed: "Látex, casca do tronco e frutos"
  },
  {
    id: "pequizeiro",
    code: "ESP-007",
    namePopular: "Pequizeiro",
    nameScientific: "Caryocar brasiliense",
    family: "Caryocaraceae",
    region: "Cerrado",
    macroRegions: ["Norte", "Nordeste", "Centro-Oeste", "Sudeste"],
    regionsSecondary: ["Caatinga"],
    shortDesc: "O rei do Cerrado: fonte incomparável de alimento, óleo tônico respiratório, antioxidantes e identidade cultural do Centro-Oeste.",
    characteristics: "Árvore tortuosa de até 10 metros de altura com folhas pubescentes divididas em três folíolos. Fruto verde globoso com caroços amarelados ricos em espinhos finos e polpa saborosa.",
    occurrence: "Em todo o bioma Cerrado, em solos secos, pobres e profundos das regiões Centro-Oeste, Sudeste e Nordeste do Brasil.",
    traditionalUse: "O óleo extraído da polpa ou da amêndoa é usado tradicionalmente para tratar bronquites, resfriados, rouquidão, além de hidratação cutânea e cicatrização de queimaduras.",
    curiosities: "O óleo de pequi é riquíssimo em carotenoides (precursores da Vitamina A) e ácidos graxos monoinstaturados. Seu caroço possui milhares de espinhos internos que exigem técnica para roer sem roer o caroço!",
    precautions: "Atenção máxima aos espinhos internos do fruto ao consumir. O óleo deve ser armazenado ao abrigo da luz para evitar oxidação.",
    sources: "Universidade de Brasília (UnB); Ministério do Meio Ambiente; Livro 'Pequi: Fruto do Cerrado'.",
    image: "assets/pequizeiro_svg",
    conservationStatus: "Protegida por leis estaduais (Corte proibido em GO/MG)",
    partUsed: "Óleo da polpa, óleo da amêndoa e casca"
  },
  {
    id: "copaiba",
    code: "ESP-008",
    namePopular: "Copaíba",
    nameScientific: "Copaifera langsdorffii",
    family: "Fabaceae",
    region: "Amazônia",
    macroRegions: ["Norte", "Nordeste", "Centro-Oeste", "Sudeste"],
    regionsSecondary: ["Cerrado", "Mata Atlântica"],
    shortDesc: "Conhecida como o 'bálsamo da Amazônia', produz um óleo-resina lendário com potente ação anti-inflamatória e antisséptica.",
    characteristics: "Árvore de grande porte (até 35 metros), de tronco reto e copa densa. Do interior de seu tronco é extraído um óleo-resina translúcido dourado a castanho.",
    occurrence: "Florestas tropicais da Amazônia, matas ciliares do Cerrado e formações da Mata Atlântica.",
    traditionalUse: "Gotas do óleo-resina tomadas com mel ou aplicadas na pele para inflamações na garganta, problemas urinários, psoríase e cicatrização de ferimentos graves.",
    curiosities: "Indígenas observavam que animais feridos na floresta se esfregavam nos troncos da copaíba para estancar sangramentos e curar machucados.",
    precautions: "Uso interno deve ser feito em doses estritamente controladas (gotas), pois doses elevadas podem causar vômitos e irritação renal.",
    sources: "INPA (Instituto Nacional de Pesquisas da Amazônia); Farmacopeia Popular Paranaense.",
    image: "assets/copaiba_svg",
    conservationStatus: "Pouco Preocupante",
    partUsed: "Óleo-resina extraído do tronco"
  },
  {
    id: "guarana",
    code: "ESP-009",
    namePopular: "Guaraná",
    nameScientific: "Paullinia cupana",
    family: "Sapindaceae",
    region: "Amazônia",
    macroRegions: ["Norte"],
    regionsSecondary: [],
    shortDesc: "Cipó nativo da bacia amazônica cujas sementes lembram olhos humanos e oferecem estímulo físico e clareza mental.",
    characteristics: "Planta trepadeira (cipó) que produz cachos de frutos vermelhos que se abrem quando maduros, revelando a arilo branco e a semente preta parecida com um olho.",
    occurrence: "Nativa da Amazônia brasileira, especialmente na região de Maués (AM) e Estado do Pará.",
    traditionalUse: "Pó das sementes torradas consumido com água como tônico revitalizante, combate à fadiga, aumento do foco e tônico cardiovascular ancestral dos Sateré-Mawé.",
    curiosities: "Contém guaranina (substância idêntica à cafeína, mas combinada a taninos que promovem uma liberação gradual e duradoura de energia no corpo).",
    precautions: "Evitar consumo excessivo à noite (causa insônia) e por pessoas hipertensas ou com arritmia cardíaca.",
    sources: "EMBRAPA Amazônia Ocidental; Conselho Indigenista Sateré-Mawé.",
    image: "assets/guarana_svg",
    conservationStatus: "Pouco Preocupante",
    partUsed: "Sementes torradas e moídas"
  },
  {
    id: "ipe-roxo",
    code: "ESP-010",
    namePopular: "Ipê-Roxo",
    nameScientific: "Handroanthus impetiginosus",
    family: "Bignoniaceae",
    region: "Mata Atlântica",
    macroRegions: ["Nordeste", "Centro-Oeste", "Sudeste", "Sul"],
    regionsSecondary: ["Cerrado", "Pantanal"],
    shortDesc: "Árvore de floração exuberante cuja entrecasca abriga o lapachol, princípio ativo estudado mundialmente por suas propriedades imunitárias.",
    characteristics: "Árvore de 8 a 30 metros de altura que perde todas as folhas no inverno para cobrir-se completamente de flores tubular-campanuladas de cor rosa-púrpura vibrante.",
    occurrence: "Ocorre na Mata Atlântica, Pantanal mato-grossense e matas secas do Cerrado.",
    traditionalUse: "Decocção da entrecasca roxa para fortalecimento do sistema imunológico, combate a fungos, alergias e inflamações dérmicas.",
    curiosities: "Os incas chamavam a árvore de 'Taheebo' e consideravam seu chá uma bebida divina de longevidade. O lapachol isolado de sua casca é referência em farmacologia.",
    precautions: "Não recomendado para grávidas e pacientes em uso de anticoagulantes sem orientação médica.",
    sources: "Sociedade Brasileira de Farmacognosia; herbários estaduais do Pantanal.",
    image: "assets/ipe_roxo_svg",
    conservationStatus: "Pouco Preocupante",
    partUsed: "Entrecasca do tronco"
  },
  {
    id: "espinheira-santa",
    code: "ESP-011",
    namePopular: "Espinheira-Santa",
    nameScientific: "Monteverdia ilicifolia",
    family: "Celastraceae",
    region: "Pampa",
    macroRegions: ["Sul", "Sudeste"],
    regionsSecondary: ["Mata Atlântica"],
    shortDesc: "Folha com espinhos na borda reverenciada no sul do Brasil pelo alívio rápido de dores estomacais e azia.",
    characteristics: "Arbusto ou pequena árvore de 2 a 5 metros com folhas coriáceas cujas margens possuem espinhos afiados parecidos com o azevinho europeu.",
    occurrence: "Campos do Pampa gaúcho e florestas de araucária da Mata Atlântica nos estados do RS, SC e PR.",
    traditionalUse: "Infusão das folhas secas para tratamento de gastrite, úlceras pépticas, azia e refluxo gastroesofágico.",
    curiosities: "Sua eficácia antiúlcera foi cientificamente comprovada pela Central de Medicamentos (CEME) do Governo Brasileiro, demonstrando proteção da mucosa estomacal superior a vários antiácidos sintéticos.",
    precautions: "Contraindicada durante a amamentação (pode reduzir a produção de leite materno) e na gestação.",
    sources: "SUS - Relação Nacional de Plantas Medicinais de Interesse ao SUS (RENISUS); UFRGS.",
    image: "assets/espinheira_santa_svg",
    conservationStatus: "Ameaçada por extrativismo em áreas nativas",
    partUsed: "Folhas"
  },
  {
    id: "sucupira-do-cerrado",
    code: "ESP-012",
    namePopular: "Sucupira-branca",
    nameScientific: "Pterodon emarginatus",
    family: "Fabaceae",
    region: "Pantanal",
    macroRegions: ["Norte", "Centro-Oeste", "Sudeste"],
    regionsSecondary: ["Cerrado"],
    shortDesc: "Sementes aromáticas ricas em óleos essenciais conhecidas em todo o Brasil rural para alívio de dores nas articulações.",
    characteristics: "Árvore de 8 a 15 metros com tronco avermelhado a acinzentado. Seus frutos são sementes aladas lenhosas alaranjadas ricas em cavidades oleosas aromáticas.",
    occurrence: "Savanas do Cerrado e formações de encosta no Pantanal e planalto central.",
    traditionalUse: "Sementes cortadas ao meio maceradas em vinho ou cachaça (ou chá fervido com leite) para reumatismo, artrite, artrose e dores na coluna.",
    curiosities: "Ao cortar uma semente de sucupira ao meio, exala-se um aroma perfumado e resinoso imediato dos diterpenos e flavonoides presentes na amêndoa.",
    precautions: "Uso prolongado em doses altas deve ser evitado por indivíduos com problemas renais ou hepáticos.",
    sources: "Universidade Federal de Mato Grosso (UFMT); Rede de Plantas Medicinais do Pantanal.",
    image: "assets/sucupira-cerrado.png",
    conservationStatus: "Pouco Preocupante",
    partUsed: "Sementes e frutos"
  }
];

const BIOMES = [
  { id: "Todos", name: "Todos os Biomas", count: 12 },
  { id: "Cerrado", name: "Cerrado", desc: "Berço das águas brasileiras e savana mais rica do planeta em biodiversidade medicinal." },
  { id: "Amazônia", name: "Amazônia", desc: "Maior floresta tropical do mundo, tesouro de árvores gigantes e bálsamos medicinais." },
  { id: "Caatinga", name: "Caatinga", desc: "Bioma exclusivamente brasileiro de alta resiliência e plantas adaptadas à seca." },
  { id: "Mata Atlântica", name: "Mata Atlântica", desc: "Biodiversidade de florestas tropicais e de altitude com rica tradição de cura popular." },
  { id: "Pantanal", name: "Pantanal", desc: "Planície alagável com flora adaptada a ciclos intensos de cheias e secas." },
  { id: "Pampa", name: "Pampa", desc: "Campos sulinos com flora medicinal adaptada ao frio e saberes pampianos." }
];

window.plantsData = plantsData;
window.BIOMES = BIOMES;
